backend:
  name: github
  repo: Marigno/marigno.com
  branch: master

media_folder: 'content/images'
public_folder: '/assets'

collections:
  - name: 'blog'
    label: 'Blog'
    folder: 'content/posts'
    create: true
    fields:
      - { name: 'title', label: 'Title', widget: 'string' }
      - { name: 'author', label: 'Author', widget: 'string' }
      - { name: 'date', label: 'Date', widget: 'datetime' }
      - { name: 'picture', label: 'Picture desc', widget: 'string' }
      - { name: 'cover', label: 'Image', widget: 'image' }
      - { name: 'body', label: 'Body', widget: 'markdown' }